In [1]:
import pandas as pd
df = pd.read_csv('tous_etablissements_avec_sites_web.csv')

df

,categorie,nom,type,statut,adresse,ville,telephone,email,site_web,lien_fiche
0,primaire,Alternative School M'saken,Primaire,Privé,Route kairouan en face du lycée khawarezmi,M'saken,+216 29 007 115,altrnativeschool@yahoo.com,NaN,https://www.ecoles.com.tn/etablissements/prima...
1,primaire,AlYosser,Primaire,Privé,Cité Eriadh sbiba,Kasserine,52571142,NaN,NaN,https://www.ecoles.com.tn/etablissements/prima...
2,primaire,Ambassadeur,Primaire,Privé,Rue Tarek Ben Ziyed,Moknine,+216 73 476 672 / 99 268 225,NaN,NaN,https://www.ecoles.com.tn/etablissements/prima...
3,primaire,British International School of Tunis,Primaire,Privé,49 rue du Parc,La Soukra,+216 70 24 08 80 / 94 23 27 20,admissions@bistunis.com,http://www.bistunis.com/,https://www.ecoles.com.tn/etablissements/prima...
4,primaire,École Canadienne de Tunis - ECT,Primaire,Privé,Croisement . Rue de l’Énergie Solaire/Rue des ...,Charguia,+216 71 20 60 35 / 26 74 99 49,contact@ec-tunis.com,http://www.ec-tunis.com,https://www.ecoles.com.tn/etablissements/prima...
...,...,...,...,...,...,...,...,...,...,...
1278,superieur,Institut Supérieur des Langues de Gabes - ISLGB,Supérieur,Public,Rue Ali Jmel,Gabès,+216 75 27 53 44 / 75 27 42 44,mongikahloul@yahoo.fr,http://www.islgb.rnu.tn/,https://www.ecoles.com.tn/etablissements/super...
1279,superieur,Institut Supérieur des Langues de Nabeul - ISLN,Supérieur,Public,Avenue Habib Thameur,Nabeul,+216 72 23 61 43 / 72 23 05 51,info@islain.rnu.tn,http://www.isln.rnu.tn/,https://www.ecoles.com.tn/etablissements/super...
1280,superieur,INSTITUT SUPÉRIEUR DES LANGUES DE TUNIS,Supérieur,Public,14 Rue Ibn Maja,Cité El Khadra,+216 71 805 760 / 71 773 813 / 71 773 423,email@islt.rnu.tn,http://www.islt.rnu.tn,https://www.ecoles.com.tn/etablissements/super...
1281,superieur,Institut Supérieur des Mathématiques Appliqués...,Supérieur,Public,Avenue Assad Ibn Fourat,Kairouan,+216 77 23 82 17,ismai@ismai.rnu.tn,NaN,https://www.ecoles.com.tn/etablissements/super...
1282,superieur,Institut Supérieur des Métiers de la Mode de M...,Supérieur,Public,Stah Jabeur,Monastir,+216 73 461 423,ismmm@ismmm.rnu.tn,http://www.ismmm.rnu.tn,https://www.ecoles.com.tn/etablissements/super...

In [3]:
df.head(20)

,categorie,nom,type,statut,adresse,ville,telephone,email,lien_fiche
0,primaire,Alternative School M'saken,Primaire,Privé,Route kairouan en face du lycée khawarezmi,M'saken,+216 29 007 115,altrnativeschool@yahoo.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
1,primaire,AlYosser,Primaire,Privé,Cité Eriadh sbiba,Kasserine,52571142,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
2,primaire,Ambassadeur,Primaire,Privé,Rue Tarek Ben Ziyed,Moknine,+216 73 476 672 / 99 268 225,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
3,primaire,British International School of Tunis,Primaire,Privé,49 rue du Parc,La Soukra,+216 70 24 08 80 / 94 23 27 20,admissions@bistunis.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
4,primaire,École Canadienne de Tunis - ECT,Primaire,Privé,Croisement . Rue de l’Énergie Solaire/Rue des ...,Charguia,+216 71 20 60 35 / 26 74 99 49,contact@ec-tunis.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
5,primaire,Ecole Mahjoub,Primaire,Privé,"32, rue du Niger",Tunis Ville,contact@ecolemahjoub.com,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
6,primaire,École primaire privée les génies,Primaire,Privé,17 rue 13 out El wardia /17 rue Ahmed maskawai...,Médina,+216 71 37 28 52,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
7,primaire,École privée Errayhane,Primaire,Privé,Route Mehdia km2 El bousten,Sfax,+216 74 21 52 64,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
8,primaire,El Académie,Primaire,Privé,1 rue taher el hadded,Le Bardo,21599064,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
9,primaire,El Amed,Primaire,Privé,Place Abderrahmen Dahmeni,Beni Hassen,+216 31 545 000 / 58 518 322,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
10,primaire,Elfaouz,Primaire,Privé,Rue sidi younes elssouk,Fériana,97 043 032,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
11,primaire,Ichrak School,Primaire,Privé,Route Kaid Mhamed km 2.5,Sfax,+216 23 06 00 06 / 55 84 52 45 / 44 94 92 49,ichrakschool@gmail.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
12,primaire,Institution ESPOIRS,Primaire,Privé,"Lot 124 ZI Chotrana2, Ariana Essoghra",Ariana Ville,+216 55 43 51 39,espoirs.ens@gmail.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
13,primaire,kounouz all ghad,Primaire,Privé,Rue de l'environement n 119 sidi hassine sedjoumi,Tunis,+216 25 30 00 71,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
14,primaire,la créativité,Primaire,Privé,"Sidi Ameur, Monastir, Tunisia",Sahline,52 730 485 / 26 333 032,contact@ecoledelacreativite.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
15,primaire,Lamis School Mourouj,Primaire,Privé,Rue de Gaza,El Mourouj,+216 50 986 912,lamischool@gmail.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
16,primaire,Les Trois Colombes,Primaire,Privé,Route Inetercommunale par la route Z4,Mégrine,+216 71 297 277 / 95 654 422,lestrois_colombes@yahoo.fr,https://www.ecoles.com.tnhttps://www.ecoles.co...
17,primaire,Mongil School,Primaire,Privé,"Rue du pakistan Mongil, Rades",Ben Arous ville,+216 71 447 911 / 71 440 602 / 20 273 768,contact@mongilschool.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
18,primaire,Salima School - Ezzahra (SLS),Primaire,Privé,Cité El Habib Ezzahra,Ezzahra,+216 54 54 86 12,contact@sls-schools.tn,https://www.ecoles.com.tnhttps://www.ecoles.co...
19,primaire,A.Q Chebbi,Primaire,Privé,rue MD NEGRA ---SAHABI 4,Kairouan,+216 77 27 31 66,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...

In [4]:
df.columns

Index(['categorie', 'nom', 'type', 'statut', 'adresse', 'ville', 'telephone',
       'email', 'lien_fiche'],
      dtype='str')

In [5]:
df.dtypes

categorie     str
nom           str
type          str
statut        str
adresse       str
ville         str
telephone     str
email         str
lien_fiche    str
dtype: object

In [6]:
df.describe

<bound method NDFrame.describe of       categorie                                                nom       type  \
0      primaire                         Alternative School M'saken   Primaire
1      primaire                                           AlYosser   Primaire
2      primaire                                        Ambassadeur   Primaire
3      primaire              British International School of Tunis   Primaire
4      primaire                    École Canadienne de Tunis - ECT   Primaire
...         ...                                                ...        ...
1485  superieur                                  UNIVERSITÉ SESAME  Supérieur
1486  superieur                    Université Tunis Carthage (UTC)  Supérieur
1487  superieur                UNIVERSITÉ VIRTUELLE DE TUNIS (UVT)  Supérieur
1488  superieur  UPSAT Université Privée des Sciences et Arts T...  Supérieur
1489  superieur            VATEL - HOTEL & TOURISM BUSINESS SCHOOL  Supérieur

      statut                                            adresse       ville  \
0      Privé         Route kairouan en face du lycée khawarezmi     M'saken
1      Privé                                  Cité Eriadh sbiba   Kasserine
2      Privé                                Rue Tarek Ben Ziyed     Moknine
3      Privé                                     49 rue du Parc   La Soukra
4      Privé  Croisement . Rue de l’Énergie Solaire/Rue des ...    Charguia
...      ...                                                ...         ...
1485   Privé   ZI Chotrana I – BP 4 parc technologique Elgazala      Raoued
1486   Privé                          Avenue Fattouma Bourguiba   La Soukra
1487  Public                      13 Rue Ibn Nadim, Montplaisir       Tunis
1488   Privé                         route manzel cheker km 0,5  Sfax Ville
1489  Public                         Zone d'activité Khereddine       Tunis

                                         telephone  \
0                                  +216 29 007 115
1                                         52571142
2                     +216 73 476 672 / 99 268 225
3                   +216 70 24 08 80 / 94 23 27 20
4                   +216 71 20 60 35 / 26 74 99 49
...                                            ...
1485             +216 70 686 486 / +216 97 397 292
1486                            (+216) 54 38 00 00
1487  +216 71 90 52 48 / 71 90 52 69 / 71 90 52 54
1488                               +216 74 460 854
1489                               +216 71 182 300

                           email  \
0     altrnativeschool@yahoo.com
1                            NaN
2                            NaN
3        admissions@bistunis.com
4           contact@ec-tunis.com
...                          ...
1485        sesame@sesame.com.tn
1486    admission@utctunisie.com
1487        webmaster@uvt.rnu.tn
1488               info@upsat.tn
1489               info@vatel.tn

                                             lien_fiche
0     https://www.ecoles.com.tnhttps://www.ecoles.co...
1     https://www.ecoles.com.tnhttps://www.ecoles.co...
2     https://www.ecoles.com.tnhttps://www.ecoles.co...
3     https://www.ecoles.com.tnhttps://www.ecoles.co...
4     https://www.ecoles.com.tnhttps://www.ecoles.co...
...                                                 ...
1485  https://www.ecoles.com.tnhttps://www.ecoles.co...
1486  https://www.ecoles.com.tnhttps://www.ecoles.co...
1487  https://www.ecoles.com.tnhttps://www.ecoles.co...
1488  https://www.ecoles.com.tnhttps://www.ecoles.co...
1489  https://www.ecoles.com.tnhttps://www.ecoles.co...

[1490 rows x 9 columns]>

In [9]:
df_privé=df[df["statut"]=="Privé"]
df_privé

,categorie,nom,type,statut,adresse,ville,telephone,email,lien_fiche
0,primaire,Alternative School M'saken,Primaire,Privé,Route kairouan en face du lycée khawarezmi,M'saken,+216 29 007 115,altrnativeschool@yahoo.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
1,primaire,AlYosser,Primaire,Privé,Cité Eriadh sbiba,Kasserine,52571142,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
2,primaire,Ambassadeur,Primaire,Privé,Rue Tarek Ben Ziyed,Moknine,+216 73 476 672 / 99 268 225,NaN,https://www.ecoles.com.tnhttps://www.ecoles.co...
3,primaire,British International School of Tunis,Primaire,Privé,49 rue du Parc,La Soukra,+216 70 24 08 80 / 94 23 27 20,admissions@bistunis.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
4,primaire,École Canadienne de Tunis - ECT,Primaire,Privé,Croisement . Rue de l’Énergie Solaire/Rue des ...,Charguia,+216 71 20 60 35 / 26 74 99 49,contact@ec-tunis.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
...,...,...,...,...,...,...,...,...,...
1483,superieur,Université Privée de Sousse (UPS),Supérieur,Privé,Campus Universitaire-Boukhzar,Sousse,+216 73 231 985 / 73 231 986 / 52 532 241,ups@ups.ens.tn,https://www.ecoles.com.tnhttps://www.ecoles.co...
1484,superieur,Université Privée des Etudes Scientifiques et ...,Supérieur,Privé,Face à la gare de Sidi-Rézig,Mégrine,+216 71 426 354 / 52 126 354,info@upes-megrine.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
1485,superieur,UNIVERSITÉ SESAME,Supérieur,Privé,ZI Chotrana I – BP 4 parc technologique Elgazala,Raoued,+216 70 686 486 / +216 97 397 292,sesame@sesame.com.tn,https://www.ecoles.com.tnhttps://www.ecoles.co...
1486,superieur,Université Tunis Carthage (UTC),Supérieur,Privé,Avenue Fattouma Bourguiba,La Soukra,(+216) 54 38 00 00,admission@utctunisie.com,https://www.ecoles.com.tnhttps://www.ecoles.co...
1488,superieur,UPSAT Université Privée des Sciences et Arts T...,Supérieur,Privé,"route manzel cheker km 0,5",Sfax Ville,+216 74 460 854,info@upsat.tn,https://www.ecoles.com.tnhttps://www.ecoles.co...

In [12]:
df_privé[df_privé["nom"] == "esprit : Ecole Sup Privée d'Ingénierie et de Technologies"]

,categorie,nom,type,statut,adresse,ville,telephone,email,lien_fiche
1271,superieur,esprit : Ecole Sup Privée d'Ingénierie et de T...,Supérieur,Privé,"1, 2 rue André Ampère - 2083 - Pôle Technologi...",Ariana,+216 70 250 000,contact@esprit.tn,https://www.ecoles.com.tnhttps://www.ecoles.co...

In [14]:
print(df.shape)

(1283, 10)

In [15]:
df.head()

,categorie,nom,type,statut,adresse,ville,telephone,email,site_web,lien_fiche
0,primaire,Alternative School M'saken,Primaire,Privé,Route kairouan en face du lycée khawarezmi,M'saken,+216 29 007 115,altrnativeschool@yahoo.com,NaN,https://www.ecoles.com.tn/etablissements/prima...
1,primaire,AlYosser,Primaire,Privé,Cité Eriadh sbiba,Kasserine,52571142,NaN,NaN,https://www.ecoles.com.tn/etablissements/prima...
2,primaire,Ambassadeur,Primaire,Privé,Rue Tarek Ben Ziyed,Moknine,+216 73 476 672 / 99 268 225,NaN,NaN,https://www.ecoles.com.tn/etablissements/prima...
3,primaire,British International School of Tunis,Primaire,Privé,49 rue du Parc,La Soukra,+216 70 24 08 80 / 94 23 27 20,admissions@bistunis.com,http://www.bistunis.com/,https://www.ecoles.com.tn/etablissements/prima...
4,primaire,École Canadienne de Tunis - ECT,Primaire,Privé,Croisement . Rue de l’Énergie Solaire/Rue des ...,Charguia,+216 71 20 60 35 / 26 74 99 49,contact@ec-tunis.com,http://www.ec-tunis.com,https://www.ecoles.com.tn/etablissements/prima...

In [16]:
# Compter les lignes où site_web n'est pas vide (et pas NaN)
df_site_ok = df[df['site_web'].notna() & (df['site_web'] != '')]
print(f"Nombre d'établissements avec site web : {len(df_site_ok)}")
print(f"Nombre d'établissements SANS site web : {len(df) - len(df_site_ok)}")

Nombre d'établissements avec site web : 341
Nombre d'établissements SANS site web : 942

In [17]:
df_site_ok[['nom', 'ville', 'site_web']]

,nom,ville,site_web
3,British International School of Tunis,La Soukra,http://www.bistunis.com/
4,École Canadienne de Tunis - ECT,Charguia,http://www.ec-tunis.com
9,El Amed,Beni Hassen,https://www.amed-sahline.tn/?fbclid=IwZXh0bgNh...
12,Institution ESPOIRS,Ariana Ville,http://www.institutionespoirs.tn
17,Mongil School,Ben Arous ville,http://www.mongilschool.com
...,...,...,...
1277,Institut Supérieur des Langues Appliquées de M...,Moknine,http://www.islaatm.rnu.tn
1278,Institut Supérieur des Langues de Gabes - ISLGB,Gabès,http://www.islgb.rnu.tn/
1279,Institut Supérieur des Langues de Nabeul - ISLN,Nabeul,http://www.isln.rnu.tn/
1280,INSTITUT SUPÉRIEUR DES LANGUES DE TUNIS,Cité El Khadra,http://www.islt.rnu.tn
1282,Institut Supérieur des Métiers de la Mode de M...,Monastir,http://www.ismmm.rnu.tn

In [18]:
df['categorie'].value_counts()

categorie
primaire      611
secondaire    480
superieur     192
Name: count, dtype: int64

In [19]:
df['statut'].value_counts()

statut
Privé     911
Public    372
Name: count, dtype: int64

In [21]:
df_prive_site = df[(df['statut'] == 'Privé') & (df['site_web'].notna()) & (df['site_web'] != '')]
print(f"Écoles privées avec site web : {len(df_prive_site)}")
df_prive_site[['nom', 'ville', 'site_web','telephone','email' ]].head(10)

Écoles privées avec site web : 192

,nom,ville,site_web,telephone,email
3,British International School of Tunis,La Soukra,http://www.bistunis.com/,+216 70 24 08 80 / 94 23 27 20,admissions@bistunis.com
4,École Canadienne de Tunis - ECT,Charguia,http://www.ec-tunis.com,+216 71 20 60 35 / 26 74 99 49,contact@ec-tunis.com
9,El Amed,Beni Hassen,https://www.amed-sahline.tn/?fbclid=IwZXh0bgNh...,+216 31 545 000 / 58 518 322,NaN
12,Institution ESPOIRS,Ariana Ville,http://www.institutionespoirs.tn,+216 55 43 51 39,espoirs.ens@gmail.com
17,Mongil School,Ben Arous ville,http://www.mongilschool.com,+216 71 447 911 / 71 440 602 / 20 273 768,contact@mongilschool.com
23,Abd Al-Rahman Ibn Khaldoun,Djerba - Houmt Souk,https://www.epparik-djerba.com/,+216 54 06 18 72,contact@epparik-djerba.com
24,Academia,Monastir Ville,https://e-academia.com.tn/,+216 73 50 27 17 / 50 182 210,contact@e-academia.com.tn
27,Académie De L'excellence,Ariana Ville,https://www.kademia.tn/,+216 70 74 15 72,info@kademia.tn
28,Académie de l'Excellence,Kélibia,https://excellencekelibia.com/,+216 72 27 55 60,contact@excellencekelibia.com
30,Académie Du Lac,Lac,https://academiedulac.tn/,+216 29 10 24 00,contact@academiedulac.com

In [22]:
# Sites web trouvés par catégorie
df_site_ok.groupby('categorie').size()

categorie
primaire      120
secondaire     40
superieur     181
dtype: int64

In [2]:
df.shape

(1283, 10)